version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-cli-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - master-branch-dependencies-{{ checksum "composer.json" }}
          - master-branch-vendor-dependencies
      - run: composer install -n --prefer-dist
      - run:
            name: Update PATH and Define Environment Variable at Runtime
            command: |
                echo 'export CLIENT_ID=${CLIENT_ID}' >> $BASH_ENV
                echo 'export CLIENT_SECRET=${CLIENT_SECRET}' >> $BASH_ENV
                echo 'export ACCESS_TOKEN=${ACCESS_TOKEN}' >> $BASH_ENV
                source $BASH_ENV
      - save_cache:
          paths:
            - ./vendor
          key: master-branch-dependencies-{{ checksum "composer.json" }}
      - run: composer run test