version: 2
jobs:
  build:
    docker:
      - image: circleci/php:5-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - php-5x-dependencies-{{ checksum "composer.json" }}
          - php-5x-dependencies-
      - run: composer install -n --prefer-dist
      - run:
            name: Update PATH and Define Environment Variable at Runtime
            command: |
                echo 'CLIENT_ID=${CLIENT_ID}' >> $BASH_ENV
                echo 'CLIENT_SECRET=${CLIENT_SECRET}' >> $BASH_ENV
                echo 'ACCESS_TOKEN=${ACCESS_TOKEN}' >> $BASH_ENV
                source $BASH_ENV
      - save_cache:
          paths:
            - ./vendor
          key: php-5x-dependencies-{{ checksum "composer.json" }}
      - run: composer run cs:fix
      - run: composer run test