version: 2
jobs:
  build:
    docker:
      - image: circleci/php:5-browsers
    test:
      parallelism: 4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - run: export CLIENT_ID=${CLIENT_ID}
      - run: export CLIENT_SECRET=${CLIENT_SECRET}
      - run: export ACCESS_TOKEN=${ACCESS_TOKEN}
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: composer run cs-fix
      - run: composer run test